#!/bin/sh

	sudo $(PKG_MGR) install chromium-browser -y
	#sudo apt-get install vim -y
	#sudo apt-get install tmux -y
	#sudo apt-get install git-core bash-completion -y

	#git clone SIMPLE_BASH -- scripts
	# unpack scripts
	#cp -R scripts/* .

	#vi 
